
{'date': 'Fri Jul 02 2021 17:21:21.126 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 21
  self.mitocondria = Elemento(MITOCONDRIA, x=200, y=200, w=600, h=200, self.cena=self.celula)
                                                                                ^
SyntaxError: keyword can't be an expression
'''},
{'date': 'Fri Jul 02 2021 17:34:30.565 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''
 module <string> line 24
  self.glicose = Elemento(GLICOSE, tit=, x=0, y=100, w=100, h=100, cena=self.celula, drag=True)
                                        ^
SyntaxError: invalid syntax
'''},
{'date': 'Fri Jul 02 2021 17:35:11.945 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    Mito()
  module <module> line 8
    self.escuro = Elemento(ESCURO, x=0, y=0, w=1000, h=600, o=0.92, cena=self.celula)
UnboundLocalError: local variable 'ESCURO' referenced before assignment
'''},
{'date': 'Fri Jul 02 2021 17:35:30.903 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    Mito()
  module <module> line 8
    self.celula = Cena(CELULA)
UnboundLocalError: local variable 'CELULA' referenced before assignment
'''},
{'date': 'Fri Jul 02 2021 17:35:34.821 GMt-0300 (Horário Padrão de Brasília) -X- SuPyGirls -X-',
'error': '''Traceback (most recent call last):
  module _core.main line 180
    dialog.action(lambda *_: self.start()
  module _core.supygirls_factory line 135
    self.act(self, lambda *_: self.hide() or extra()) if self.act else None
  module _core.supygirls_factory line 310
    return self._first_response(lambda: self._executa_acao(), self.extra, self.error)
  module _core.supygirls_factory line 282
    traceback.print_exc(file=sys.stderr)
  module _core.supygirls_factory line 299
    exec(self.code, glob)  # dict(__name__="__main__"))
  module <module> line 28
    Mito()
  module <module> line 8
    self.celula = Cena(CELULA)
UnboundLocalError: local variable 'CELULA' referenced before assignment
'''},